version: "3.3"

services:
  db:
    image: "postgres:12"
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}

  wallet:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 80:3000
    depends_on:
      # The db container needs to be started before we start this container
      - db
    command: npm start
