version: "3.3"

services:
  pg:
    image: "postgres:12"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data

  wallet:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 80:3000
    depends_on:
      # The db container needs to be started before we start this container
      - pg
    command: npm start
volumes:
  dbdata:
