import models from '../models'
import bcrypt from 'bcrypt';
import crypto from 'crypto';
import jwt from 'jsonwebtoken';
import fetch from 'node-fetch';
import queryString from 'query-string';
import AWS from 'aws-sdk';
import fs from 'fs';
import path from 'path';

// Hellosign 
const hellosign = require('hellosign-sdk')({ key: process.env.HELLOSIGN_API_KEY });

console.log(process.env);

// Retrieve the requested pdf
const getPDF = async (hellosign_signature_request_id, parent_res) => {
    try {
        // Returning undefined
        await hellosign.signatureRequest.download(hellosign_signature_request_id, { get_url: true }, (err, res) => {

            if (err) {
                console.log(err);
                return parent_res.status(400).json("Couldn't fetch hellosign")
            }

            return parent_res.status(200).json(res).send();
          }) 

    } catch (e) {
        console.log(e);
        return parent_res.status(500).json(err).send();
    }
}


// Submit the autogenerated pdf to hellosign
const submitPDF = async (requisition, res) => {

    // Find the brand owner
    const brand_owner = requisition.client.client_collaborators.find(collaborator => collaborator.role.name === 'OWNER');
      
    const opts = {
        test_mode: 1,
        clientId: process.env.HELLOSIGN_CLIENT_ID,
        subject: `ACTION NEEDED - Requisition #${requisition.serial_number}`,
        message: 'Please sign this requisition.',
        signers: [
            {
             email_address: brand_owner.account.email,
             name: `${brand_owner.account.first_name} ${brand_owner.account.last_name}`
            }
        ],
        files: [`temporal/${requisition.client.id}_${requisition.serial_number}.pdf`]
    };
    
    return await hellosign.signatureRequest.createEmbedded(opts).then(async (res) => {
        const signature_request_id = res.signature_request.signature_request_id;
        const signature = res.signature_request.signatures[0];
        const signatureId = signature.signature_id;
      
        const url_object = await hellosign.embedded.getSignUrl(signatureId);
        return {url: url_object.embedded.sign_url , signature_request_id};
    }).then((signature) => {
        return signature;
    }).catch((err) => {
        // handle error
        return res.status(500).json(err).send();
    });
}

export {
    getPDF,
    submitPDF,
}