export default 
[ 
    // Languages
    { name: 'Javascript', variations: [ 'Javascript' ] },
    { name: 'Typescript', variations: [ 'Typescript' ] },
    { name: 'PHP', variations: [ 'PHP' ] },
    { name: 'Java', variations: [ ' Java ' ] },
    { name: 'Ruby', variations: [ 'Ruby' ] },
    { name: 'Go', variations: [ ' Go ', 'Golang' ] },
    { name: 'Scala', variations: [ ' Scala ' ] },
    { name: 'Python', variations: [ 'Python' ] },
    { name: 'Kotlin', variations: [ 'Kotlin' ] },
    { name: 'Sql', variations: [ ' SQL ' ] },
    { name: 'C', variations: [ ' C ' ] },
    { name: 'C++', variations: [ 'C++' ] },
    { name: 'C#', variations: [ 'C#' ] },
    { name: 'Erlang', variations: [ 'Erlang' ] },
    { name: 'Swift', variations: [ 'Swift' ] },
    { name: 'Rust', variations: [ ' Rust' ] },
    { name: 'R', variations: [ ' R ' ] },
    { name: 'ASP.NET', variations: [ 'ASP.NET', ' .NET' ] },
    { name: 'Objective-C',
        variations: [ 'Objective-C', 'Objective C' ] },
    { name: 'Elixir', variations: [ 'Elixir' ] },
    { name : 'Haskell', variations: ['Haskell']},
    // Cli
    { name: 'Bash', variations: [ ' Bash ' ] },
    { name : 'Powershell', variations: ['Powershell']},
    // Front-end
    { name: 'jQuery', variations: [ 'jQuery' ] },
    { name: 'React',
        variations: [ 'React', 'ReactJS', 'React.JS' ] },
    { name: 'Preact',
        variations: [ 'Preact', 'PreactJS', 'Preact.js' ] },
    { name: 'Redux', variations: [ 'Redux' ] },
    { name: 'Angular',
        variations: [ 'Angular', 'AngularJS', 'Angular.JS' ] },
    { name: 'Vue', variations: [ 'Vue', 'VueJS', 'Vue.JS' ] },
    { name: 'Ember',
        variations: [ ' Ember', ' EmberJS', ' Ember.js' ] },
    // Static Generators
    { name: 'Gatsby',
        variations: [ 'Gatsby', 'GatsbyJS', 'Gatsby.JS' ] },
    { name: 'Next', variations: [ 'Next.JS', 'NextJS' ] },
    { name: 'Hugo', variations: [ 'Hugo' ] },
    { name: 'Nuxt', variations: [ 'Nuxt', 'NuxtJS', 'Nuxt.JS' ] },
    // Deployment
    { name: 'Netlify', variations: [ 'Netlify' ] },
    { name: 'Zeit', variations: [ ' Zeit ' ] },
    { name: 'Github Pages', variations: [ 'Github Page' ] },
    { name: 'Stackbit', variations: [ 'Stackbit' ] },
    { name: 'Headless CMS', variations: [ 'Headless CMS' ] },
    // Mobile
    { name: 'Android', variations: [ 'Android' ] },
    { name: 'iOS', variations: [ ' iOS ' ] },
    { name: 'React Native',
        variations: [ 'React Native', 'React-Native', ' RN ' ] },
    { name: 'Flutter', variations: [ 'Flutter' ] },
    { name: 'Cordova', variations: [ 'Cordova' ] },
    { name: 'Ionic', variations: [ 'Ionic' ] },
    // Backend
    { name: 'Ruby on Rails',
        variations: [ 'Ruby on Rails', 'Ruby-on-Rails', 'Rails', ' RoR ' ] },
    { name: 'Node', variations: [ ' Node ', 'NodeJS', 'Node.JS' ] },
    { name: 'Apollo', variations: [ 'Apollo' ] },
    { name: 'Express',
        variations: [ ' Express ', 'ExpressJS', 'Express.JS' ] },
    { name: 'GraphQL', variations: [ 'GraphQL' ] },
    { name: 'Flask', variations: [ 'Flask' ] },
    { name: 'gRPC', variations: [ 'gRPC' ] },
    { name: 'Django', variations: [ 'Django' ] },
    { name: 'Laravel', variations: [ 'Laravel' ] },
    // Database 
    { name: 'MySQL', variations: [ 'MySQL' ] },
    { name: 'PostgreSQL', variations: [ 'PostgreSQL', 'Postgres' ] },
    { name: 'Oracle', variations: [ 'Oracle' ] },
    { name: 'MongoDB', variations: [ 'MongoDB', 'Mongo' ] },
    { name: 'Redis', variations: [ 'Redis' ] },
    { name: 'SQL Server', variations: [ 'SQL Server' ] },
    { name: 'BigQuery', variations: [ 'BigQuery' ] },
    { name: 'Elasticsearch', variations: [ 'Elasticsearch' ] },
    { name: 'Neo4j', variations: [ 'Neo4j' ] },
    // Big data
    { name: 'Hadoop', variations: [ 'Hadoop' ] },
    { name: 'Spark', variations: [ 'Spark' ] },
    // OS
    { name: 'Linux', variations: [ 'Linux' ] },
    { name: 'Ubuntu', variations: [ 'Ubuntu' ] },
    // Cloud Provider
    { name: 'AWS', variations: [ 'AWS', 'Amazon Web Services' ] },
    { name: 'GCP',
        variations: [ 'GCP', 'Google Cloud', 'Google Cloud Platform' ] },
    { name: 'Firebase', variations: ['Firebase']},
    { name: 'Heroku', variations: [ 'Heroku' ] },
    { name: 'Azure', variations: [ 'Azure', 'Windows Azure' ] },
    // DevOPS
    { name: 'Docker', variations: [ 'Docker' ] },
    { name: 'Kubernetes', variations: [ 'Kubernetes' ] },
    { name: 'Jenkins', variations: [ 'Jenkins' ] },
    { name: 'Vagrant', variations: [ 'Vagrant' ] },
    { name: 'Ansible', variations: [ 'Ansible' ] },
    { name: 'Terraform', variations: [ 'Terraform' ] },
    { name: 'Helm', variations: [ ' Helm ' ] },
    { name: 'Kafka', variations: [ 'Kafka' ] },
    // Misc
    { name: 'Unity', variations: [ ' Unity ', 'Unity3D' ] },
    // Workflow
    { name: 'Git', variations: [ ' Git' ] },
    { name: 'Github', variations: [ 'Github' ] },
    { name: 'Confluence', variations: [ 'Confluence' ] },
    { name: 'Jira', variations: [ 'Jira' ] },
    // Popular Libraries
    { name: 'D3', variations: [ ' D3 ', 'D3.js' ] },
    { name: 'NumPY', variations: [ 'NumPy' ] },
    // Testing
    { name: 'QA', variations: [ ' QA ', 'Quality Assurance' ] },
    // Integrations
    { name: 'Drupal', variations: [ 'Drupal' ] },
    { name: 'Magento', variations: [ 'Magento' ] },
    { name: 'Salesforce', variations: [ 'Salesforce' ] },
    { name: 'Shopify', variations: [ 'Shopify' ] },
    { name: 'Wordpress', variations: [ 'Wordpress', ' WP ' ] },
    // Crypto
    { name: 'Bitcoin', variations: [ 'Bitcoin', ' BTC ' ] },
    { name: 'Ethereum', variations: [ 'Ethereum', ' ETH ' ] },
    { name: 'Solidity', variations: [ 'Solidity' ] } 
]